/* eslint-disable @fnando/consistent-import/consistent-import */
import { TransactionBuilder, xdr } from "@stellar/stellar-sdk";
import { NETWORKS } from "config/constants";
import { readRouteTokens, verifyAggregatorSwap } from "helpers/aggregatorSwap";

import {
  CONTRACT,
  ISSUER,
  SENDER,
  USDC_SAC,
  XLM_SAC,
} from "../../__mocks__/swapFixtures";

/**
 * A real, unsigned, simulated aggregator envelope for 10 XLM to USDC on pubnet,
 * as returned by the XOXNO quote server. It carries no secret: the sender is the
 * public USDC issuer account and nothing here is signed.
 */
const fx = {
  envelopeXdr:
    "AAAAAgAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQABfugAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAYAAAAAAAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAABBleGVjdXRlX3N0cmF0ZWd5AAAAAwAAABIAAAAAAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACgAAAAAAAAAAAAAAAAX14QAAAAANAAABSAAAABEAAAABAAAAAwAAAA8AAAAHYW1vdW50cwAAAAAQAAAAAQAAAAEAAAAKAAAAAAAAAAAAAAAAAVqsPwAAAA8AAAAGYXNzZXRzAAAAAAAQAAAAAQAAAAUAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABIAAAABhDeX/AlCg4g2EDcL9jqlFn5WSSuV5S+cUNSZf7lSU4oAAAASAAAAAUD8gy1oeX3V966XgHYsr+57orEhJaMb8empceeR4JTsAAAAEgAAAAFY4iaOUj+gXi8kBRxKw6BYjS8kxUqaTDrviu3bEsSyjgAAAA8AAAADb3BzAAAAAA0AAAAUAQABAAAAAAACAAEAAgADAQEEAwEAAAABAAAAAAAAAAAAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQZXhlY3V0ZV9zdHJhdGVneQAAAAMAAAASAAAAAAAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAoAAAAAAAAAAAAAAAAF9eEAAAAADQAAAUgAAAARAAAAAQAAAAMAAAAPAAAAB2Ftb3VudHMAAAAAEAAAAAEAAAABAAAACgAAAAAAAAAAAAAAAAFarD8AAAAPAAAABmFzc2V0cwAAAAAAEAAAAAEAAAAFAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABIAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAASAAAAAYQ3l/wJQoOINhA3C/Y6pRZ+VkkrleUvnFDUmX+5UlOKAAAAEgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABIAAAABWOImjlI/oF4vJAUcSsOgWI0vJMVKmkw674rt2xLEso4AAAAPAAAAA29wcwAAAAANAAAAFAEAAQAAAAAAAgABAAIAAwEBBAMBAAAAAQAAAAAAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAIdHJhbnNmZXIAAAADAAAAEgAAAAAAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAACgAAAAAAAAAAAAAAAAX14QAAAAAAAAAAAQAAAAAAAAAQAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABQAAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAANQXBwcm92ZWRQb29scwAAAAAAABIAAAABWOImjlI/oF4vJAUcSsOgWI0vJMVKmkw674rt2xLEso4AAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAANQXBwcm92ZWRQb29scwAAAAAAABIAAAABhDeX/AlCg4g2EDcL9jqlFn5WSSuV5S+cUNSZf7lSU4oAAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAANQXBwcm92ZWRQb29scwAAAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAAPQXBwcm92ZWRSb3V0ZXJzAAAAABIAAAABWOImjlI/oF4vJAUcSsOgWI0vJMVKmkw674rt2xLEso4AAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAAPQXBwcm92ZWRSb3V0ZXJzAAAAABIAAAABhDeX/AlCg4g2EDcL9jqlFn5WSSuV5S+cUNSZf7lSU4oAAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAAPQXBwcm92ZWRSb3V0ZXJzAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAAHVmF1bHRlZAAAAAASAAAAAVjiJo5SP6BeLyQFHErDoFiNLyTFSppMOu+K7dsSxLKOAAAAAQAAAAYAAAABQPyDLWh5fdX3rpeAdiyv7nuisSEloxvx6alx55HglOwAAAAQAAAAAQAAAAIAAAAPAAAAB1ZhdWx0ZWQAAAAAEgAAAAGEN5f8CUKDiDYQNwv2OqUWflZJK5XlL5xQ1Jl/uVJTigAAAAEAAAAGAAAAAYAXaRDA7RMaHB4h/Yq7yUYY5mSDRjSws/py7vBLlyOEAAAAFAAAAAEAAAAGAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAFAAAAAEAAAAGAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAFAAAAAEAAAAHGOt2boftV4iSgoy7jBSBdzHdjlcM84YXcfuUS4XDUugAAAAHV+UQmUlMjIcxPduG2jTIVdZCMTh3z0IiQV5/eERyGHgAAAAHrg2lqEsVgFxceTGsVnqNGzS+Pya0g5k9n/gMssPemFIAAAAHvvpk2dVv66MuGOCfHDZLik2GMBYze7kzuhLMXAqOWwgAAAAOAAAAAAAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGEN5f8CUKDiDYQNwv2OqUWflZJK5XlL5xQ1Jl/uVJTigAAAAEAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAVjiJo5SP6BeLyQFHErDoFiNLyTFSppMOu+K7dsSxLKOAAAAAQAAAAYAAAABQPyDLWh5fdX3rpeAdiyv7nuisSEloxvx6alx55HglOwAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGEN5f8CUKDiDYQNwv2OqUWflZJK5XlL5xQ1Jl/uVJTigAAAAEAAAAGAAAAAUD8gy1oeX3V966XgHYsr+57orEhJaMb8empceeR4JTsAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAFA/IMtaHl91feul4B2LK/ue6KxISWjG/HpqXHnkeCU7AAAABAAAAABAAAAAgAAAA8AAAAHVmF1bHRlZAAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABQPyDLWh5fdX3rpeAdiyv7nuisSEloxvx6alx55HglOwAAAAUAAAAAQAAAAYAAAABWOImjlI/oF4vJAUcSsOgWI0vJMVKmkw674rt2xLEso4AAAAUAAAAAQAAAAYAAAABgBdpEMDtExocHiH9irvJRhjmZINGNLCz+nLu8EuXI4QAAAAQAAAAAQAAAAIAAAAPAAAACFBvb2xEYXRhAAAAEgAAAAFY4iaOUj+gXi8kBRxKw6BYjS8kxUqaTDrviu3bEsSyjgAAAAEAAAAGAAAAAYAXaRDA7RMaHB4h/Yq7yUYY5mSDRjSws/py7vBLlyOEAAAAEAAAAAEAAAACAAAADwAAAAhQb29sRGF0YQAAABIAAAABhDeX/AlCg4g2EDcL9jqlFn5WSSuV5S+cUNSZf7lSU4oAAAABAAAABgAAAAGEN5f8CUKDiDYQNwv2OqUWflZJK5XlL5xQ1Jl/uVJTigAAABQAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAVjiJo5SP6BeLyQFHErDoFiNLyTFSppMOu+K7dsSxLKOAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEBPbOgAAABTAAAHJgAAAAAAAF+hAAAAAA=",
  sender: ISSUER,
  sourceToken: XLM_SAC,
  destinationToken: USDC_SAC,
  sourceAmount: 100000000n,
  minDestinationAmount: 22719551n,
  feeStroops: 98024n,
  resourceFeeStroops: 97924n,
};

/**
 * A real, unsigned, simulated envelope for 100 XLM to deJTRSY, a Soroban-native token
 * with 18 decimals, from the same server and sender as the fixture above.
 */
const sorobanFx = {
  envelopeXdr:
    "AAAAAgAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAGi2MAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAYAAAAAAAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAABBleGVjdXRlX3N0cmF0ZWd5AAAAAwAAABIAAAAAAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAACgAAAAAAAAAAAAAAADuaygAAAAANAAAB9AAAABEAAAABAAAAAwAAAA8AAAAHYW1vdW50cwAAAAAQAAAAAQAAAAEAAAAKAAAAAAAAAAE0cDdvU0xtpQAAAA8AAAAGYXNzZXRzAAAAAAAQAAAAAQAAAAkAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEgAAAAFR+gj9UaVYRd0/JUFmk8gCJE8rieEMzsvU1cjn+pgj5AAAABIAAAABJ0TcdHflKUwKlSvcU9GUw8D0FUHgOuvQmK7g89P0lssAAAASAAAAAean2et1IwBqRpqnSDrREHJHRDwNguYnY95nCEjE6XyQAAAAEgAAAAGe3jWygpe1rfOT5lVhV47KFe/gosnnzyfcB64x57wE3gAAABIAAAABy5pWXcNXen6kap1BkccSTKg2tA2H9TG+J/MXKfh5VxoAAAASAAAAARIIRw/rYKWrw0tmjgKn2y69mxT68Kn9NmMiP7ytL7kaAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABIAAAAB2JjE/WASsP59lAFoOcv9E7CAJp0jKqkE8Ag5XJIY0oAAAAAPAAAAA29wcwAAAAANAAAAHgEAAQAAAAAABAAAAAIAAwEBBAMFAQEGBQcDAQgHAQAAAAAAAQAAAAAAAAAAAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAEGV4ZWN1dGVfc3RyYXRlZ3kAAAADAAAAEgAAAAAAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAKAAAAAAAAAAAAAAAAO5rKAAAAAA0AAAH0AAAAEQAAAAEAAAADAAAADwAAAAdhbW91bnRzAAAAABAAAAABAAAAAQAAAAoAAAAAAAAAATRwN29TTG2lAAAADwAAAAZhc3NldHMAAAAAABAAAAABAAAACQAAABIAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAASAAAAAVH6CP1RpVhF3T8lQWaTyAIkTyuJ4QzOy9TVyOf6mCPkAAAAEgAAAAEnRNx0d+UpTAqVK9xT0ZTDwPQVQeA669CYruDz0/SWywAAABIAAAAB5qfZ63UjAGpGmqdIOtEQckdEPA2C5idj3mcISMTpfJAAAAASAAAAAZ7eNbKCl7Wt85PmVWFXjsoV7+CiyefPJ9wHrjHnvATeAAAAEgAAAAHLmlZdw1d6fqRqnUGRxxJMqDa0DYf1Mb4n8xcp+HlXGgAAABIAAAABEghHD+tgpavDS2aOAqfbLr2bFPrwqf02YyI/vK0vuRoAAAASAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEgAAAAHYmMT9YBKw/n2UAWg5y/0TsIAmnSMqqQTwCDlckhjSgAAAAA8AAAADb3BzAAAAAA0AAAAeAQABAAAAAAAEAAAAAgADAQEEAwUBAQYFBwMBCAcBAAAAAAABAAAAAAAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAAAh0cmFuc2ZlcgAAAAMAAAASAAAAAAAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAKAAAAAAAAAAAAAAAAO5rKAAAAAAAAAAABAAAAAAAAABYAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAFAAAAAEAAAAGAAAAAVH6CP1RpVhF3T8lQWaTyAIkTyuJ4QzOy9TVyOf6mCPkAAAAEAAAAAEAAAACAAAADwAAAAdCbG9ja2VkAAAAABIAAAAAAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAQAAAAYAAAABUfoI/VGlWEXdPyVBZpPIAiRPK4nhDM7L1NXI5/qYI+QAAAAQAAAAAQAAAAIAAAAPAAAAB0Jsb2NrZWQAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAVH6CP1RpVhF3T8lQWaTyAIkTyuJ4QzOy9TVyOf6mCPkAAAAEAAAAAEAAAACAAAADwAAAAdCbG9ja2VkAAAAABIAAAAB2JjE/WASsP59lAFoOcv9E7CAJp0jKqkE8Ag5XJIY0oAAAAABAAAABgAAAAFR+gj9UaVYRd0/JUFmk8gCJE8rieEMzsvU1cjn+pgj5AAAABQAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABQAAAABAAAABgAAAAGe3jWygpe1rfOT5lVhV47KFe/gosnnzyfcB64x57wE3gAAABAAAAABAAAAAgAAAA8AAAAJVGlja0NodW5rAAAAAAAABP////wAAAABAAAABgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAABQAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABQAAAABAAAABgAAAAHLmlZdw1d6fqRqnUGRxxJMqDa0DYf1Mb4n8xcp+HlXGgAAABQAAAABAAAABgAAAAHYmMT9YBKw/n2UAWg5y/0TsIAmnSMqqQTwCDlckhjSgAAAABAAAAABAAAAAgAAAA8AAAAKVGlja0JpdG1hcAAAAAAABP///50AAAABAAAABgAAAAHmp9nrdSMAakaap0g60RByR0Q8DYLmJ2PeZwhIxOl8kAAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAARIIRw/rYKWrw0tmjgKn2y69mxT68Kn9NmMiP7ytL7kaAAAAAQAAAAYAAAAB5qfZ63UjAGpGmqdIOtEQckdEPA2C5idj3mcISMTpfJAAAAAUAAAAAQAAAAYAAAAB9qiow41s+9Q7rddGQUy/r59DR974iuR8vdoGKlGsF9MAAAAUAAAAAQAAAAcANxCzg/nafWUKf3Gae+R5EQJmQngX677WHZJFBfzXxwAAAAcS/KWnqWV3JzttQYTPnJhANs2g6PBZR0fnspM9ztN+5gAAAAcYBRRWgWtm8S53Olb3fFeU+sGx+3q24i1PrVpBJ3D3PgAAAAcY63Zuh+1XiJKCjLuMFIF3Md2OVwzzhhdx+5RLhcNS6AAAAAdX5RCZSUyMhzE924baNMhV1kIxOHfPQiJBXn94RHIYeAAAAAda/RV3QUsxg/c7G/8LU2Eat7px/DlIyHTliNVklqFnfQAAAAeflMV36iTC9xy7DJZMnJ0yHgJEjR/pRgIK+xiXSxwmAgAAAAfxB34Ld9peYtWW4Trq5BYBBMrZnn738xg6bJtuyedHzQAAABQAAAAAAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAABgAAAAESCEcP62Clq8NLZo4Cp9suvZsU+vCp/TZjIj+8rS+5GgAAABQAAAABAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAASdE3HR35SlMCpUr3FPRlMPA9BVB4Drr0Jiu4PPT9JbLAAAAAQAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAASdE3HR35SlMCpUr3FPRlMPA9BVB4Drr0Jiu4PPT9JbLAAAAFAAAAAEAAAAGAAAAAVH6CP1RpVhF3T8lQWaTyAIkTyuJ4QzOy9TVyOf6mCPkAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAAAAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAQAAAAYAAAABUfoI/VGlWEXdPyVBZpPIAiRPK4nhDM7L1NXI5/qYI+QAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAVH6CP1RpVhF3T8lQWaTyAIkTyuJ4QzOy9TVyOf6mCPkAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAAB2JjE/WASsP59lAFoOcv9E7CAJp0jKqkE8Ag5XJIY0oAAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABAAAAABAAAAAgAAAA8AAAAIUG9vbERhdGEAAAASAAAAARIIRw/rYKWrw0tmjgKn2y69mxT68Kn9NmMiP7ytL7kaAAAAAQAAAAYAAAABnt41soKXta3zk+ZVYVeOyhXv4KLJ588n3AeuMee8BN4AAAAUAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAESCEcP62Clq8NLZo4Cp9suvZsU+vCp/TZjIj+8rS+5GgAAAAEAAAAGAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAdiYxP1gErD+fZQBaDnL/ROwgCadIyqpBPAIOVySGNKAAAAAAQAAAAYAAAABy5pWXcNXen6kap1BkccSTKg2tA2H9TG+J/MXKfh5VxoAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAESCEcP62Clq8NLZo4Cp9suvZsU+vCp/TZjIj+8rS+5GgAAAAEAAAAGAAAAAcuaVl3DV3p+pGqdQZHHEkyoNrQNh/UxvifzFyn4eVcaAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABnt41soKXta3zk+ZVYVeOyhXv4KLJ588n3AeuMee8BN4AAAABAAAABgAAAAHLmlZdw1d6fqRqnUGRxxJMqDa0DYf1Mb4n8xcp+HlXGgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAAB2JjE/WASsP59lAFoOcv9E7CAJp0jKqkE8Ag5XJIY0oAAAAAUAAAAAQAAAAYAAAAB5qfZ63UjAGpGmqdIOtEQckdEPA2C5idj3mcISMTpfJAAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAEnRNx0d+UpTAqVK9xT0ZTDwPQVQeA669CYruDz0/SWywAAAAEAAAAGAAAAAean2et1IwBqRpqnSDrREHJHRDwNguYnY95nCEjE6XyQAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABnt41soKXta3zk+ZVYVeOyhXv4KLJ588n3AeuMee8BN4AAAABAAAABgAAAAHmp9nrdSMAakaap0g60RByR0Q8DYLmJ2PeZwhIxOl8kAAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQJDAMMAAAFMAAAoiAAAAAAABor/AAAAAA==",
  destinationToken: CONTRACT,
  minDestinationAmount: 22225325112351813029n,
};

const expected = {
  network: NETWORKS.PUBLIC,
  sender: fx.sender,
  sourceToken: fx.sourceToken,
  destinationToken: fx.destinationToken,
  sourceAmount: fx.sourceAmount,
  minDestinationAmount: fx.minDestinationAmount,
};

describe("verifyAggregatorSwap", () => {
  it("accepts the envelope the aggregator returned and reports its fees", () => {
    const verified = verifyAggregatorSwap(fx.envelopeXdr, expected);

    expect(verified.feeStroops).toBe(fx.feeStroops);
    expect(verified.resourceFeeStroops).toBe(fx.resourceFeeStroops);
  });

  it("accepts a lower expected minimum than the route promises", () => {
    expect(() =>
      verifyAggregatorSwap(fx.envelopeXdr, {
        ...expected,
        minDestinationAmount: fx.minDestinationAmount - 1n,
      }),
    ).not.toThrow();
  });

  const rejects: Record<string, Partial<typeof expected>> = {
    "another sender": {
      sender: SENDER,
    },
    "another input amount": { sourceAmount: fx.sourceAmount + 1n },
    "a minimum above the route's promise": {
      minDestinationAmount: fx.minDestinationAmount + 1n,
    },
    "another destination token": {
      destinationToken: XLM_SAC,
    },
    "another source token": {
      sourceToken: USDC_SAC,
    },
    "a network with another router": { network: NETWORKS.TESTNET },
    "a network without a router": { network: NETWORKS.FUTURENET },
  };

  Object.entries(rejects).forEach(([name, override]) => {
    it(`rejects an envelope checked against ${name}`, () => {
      expect(() =>
        verifyAggregatorSwap(fx.envelopeXdr, { ...expected, ...override }),
      ).toThrow(/Unsafe swap transaction/);
    });
  });

  it("rejects malformed input", () => {
    expect(() => verifyAggregatorSwap("AAAA", expected)).toThrow();
  });

  describe("to a Soroban-native token", () => {
    const sorobanExpected = {
      ...expected,
      sourceAmount: 1000000000n,
      destinationToken: sorobanFx.destinationToken,
      minDestinationAmount: sorobanFx.minDestinationAmount,
    };

    it("accepts the envelope the aggregator returned", () => {
      expect(() =>
        verifyAggregatorSwap(sorobanFx.envelopeXdr, sorobanExpected),
      ).not.toThrow();
    });

    it("rejects it when the token bought is another contract", () => {
      expect(() =>
        verifyAggregatorSwap(sorobanFx.envelopeXdr, {
          ...sorobanExpected,
          destinationToken: fx.destinationToken,
        }),
      ).toThrow(/Unsafe swap transaction/);
    });

    it("rejects it when the wallet expects more than the route promises", () => {
      expect(() =>
        verifyAggregatorSwap(sorobanFx.envelopeXdr, {
          ...sorobanExpected,
          minDestinationAmount: sorobanFx.minDestinationAmount + 1n,
        }),
      ).toThrow(/Unsafe swap transaction/);
    });
  });
});

describe("readRouteTokens", () => {
  const payloadOf = (envelopeXdr: string): Uint8Array => {
    const tx = TransactionBuilder.fromXDR(
      envelopeXdr,
      "Public Global Stellar Network ; September 2015",
    );
    const [op] = tx.operations;
    if (op.type !== "invokeHostFunction") throw new Error("not an invocation");
    if (op.func.type !== "hostFunctionTypeInvokeContract") {
      throw new Error("not a contract call");
    }
    const payload = op.func.invokeContract.args[2];
    if (payload.type !== "scvBytes") throw new Error("no payload");

    return payload.bytes.toBytes();
  };

  it("names the input and output token of a real route", () => {
    expect(readRouteTokens(payloadOf(fx.envelopeXdr))).toEqual({
      tokenIn: fx.sourceToken,
      tokenOut: fx.destinationToken,
    });
  });

  it("reads a route to a Soroban token", () => {
    expect(readRouteTokens(payloadOf(sorobanFx.envelopeXdr))).toEqual({
      tokenIn: fx.sourceToken,
      tokenOut: sorobanFx.destinationToken,
    });
  });

  it.each([
    ["not XDR", new Uint8Array([1, 2, 3])],
    ["not a struct", xdr.ScVal.scvU32(1).toXDR()],
    ["a struct without the route fields", xdr.ScVal.scvMap([]).toXDR()],
  ])("returns null for a payload that is %s", (_, payload) => {
    expect(readRouteTokens(payload)).toBeNull();
  });
});
