import { Horizon, nativeToScVal, xdr } from "@stellar/stellar-sdk";

/**
 * Real Stellar mainnet history records, as the Freighter backend serves them
 * (`/account-history/<G>?network=PUBLIC`), cut down to the fields the wallet
 * reads: the operation's identity, its `asset_balance_changes` and the
 * `transaction_attr` fee, operation count and `envelope_xdr`. The backend sets
 * no `contractId`, `fnName` or `args` for these calls. The account is a real
 * account that swapped through the XOXNO router.
 */

export const SWAPPER =
  "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC";
export const ROUTER =
  "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR";
/** Matrixdock Gold, a Soroban token with 9 decimals (backend token details). */
export const XAUM_CONTRACT =
  "CC2RBGYNCFBCVENIDL5BFBWPH4OUZM2UA3OD2K2N54GLMWCC4KWPVAGO";
/** Aquarius pool share tokens, Soroban tokens with 7 decimals. */
export const POOL_TOKEN_IN =
  "CCYD4C2WFWIIDF235SCDXEWL5RT6S53WQWLDHUTQ5USZ5VNF5NHJGVW7";
export const POOL_TOKEN_OUT =
  "CAPPL34NF6X7M3EQFIPDXZHQX2PT3EOE2LYCDORH3PF2LTRDSFGWV6NL";

/** tx 2879ff4c: 10 XLM for 2.3156637 USDT0 (classic to classic through USDC). The balance changes hold both user legs. */
export const xlmToUsdt0 = {
  id: "277800486161022977",
  transaction_successful: true,
  source_account: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
  type: "invoke_host_function",
  type_i: 24,
  created_at: "2026-09-29T13:21:51Z",
  transaction_hash:
    "2879ff4c3a83464bf446fd4f6f019b526fc133406883decea35cef9bac4854c3",
  asset_balance_changes: [
    {
      asset_type: "native",
      type: "transfer",
      from: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "10.0000000",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CA6PUJLBYKZKUEKLZJMKBZLEKP2OTHANDEOWSFF44FTSYLKQPIICCJBE",
      amount: "10.0000000",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CA6PUJLBYKZKUEKLZJMKBZLEKP2OTHANDEOWSFF44FTSYLKQPIICCJBE",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "2.3168411",
    },
    {
      asset_type: "credit_alphanum12",
      asset_code: "USDT0",
      asset_issuer: "GATISXX6BZ6NC7IKQBY37CJD4SOZL3CYZJWXEDG6JVIY4WBS6KXJHN6Q",
      type: "transfer",
      from: "CBVHBZSZOS6KRDJ4D44FU2YLIENOVSSLM3UGKW6XQMVIFUAMWIWCVH2U",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "2.3156637",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CBVHBZSZOS6KRDJ4D44FU2YLIENOVSSLM3UGKW6XQMVIFUAMWIWCVH2U",
      amount: "2.3168411",
    },
    {
      asset_type: "credit_alphanum12",
      asset_code: "USDT0",
      asset_issuer: "GATISXX6BZ6NC7IKQBY37CJD4SOZL3CYZJWXEDG6JVIY4WBS6KXJHN6Q",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
      amount: "2.3156637",
    },
  ],
  transaction_attr: {
    fee_charged: "78345",
    operation_count: 1,
    envelope_xdr:
      "AAAAAgAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QABXakDsoV+AAAAegAAAAEAAAAAAAAAAAAAAABqu7vUAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQZXhlY3V0ZV9zdHJhdGVneQAAAAMAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAoAAAAAAAAAAAAAAAAF9eEAAAAADQAAAUgAAAARAAAAAQAAAAMAAAAPAAAAB2Ftb3VudHMAAAAAEAAAAAEAAAABAAAACgAAAAAAAAAAAAAAAAFazw8AAAAPAAAABmFzc2V0cwAAAAAAEAAAAAEAAAAFAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABIAAAABZJyRDui+oWpF2xUm3umVum3WbQ34CbFURsOmR4lTOR0AAAASAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABIAAAABanDmWXS8qI08HzhaawtBGurKS2boZVvXgyqC0AyyLCoAAAAPAAAAA29wcwAAAAANAAAAFAEAAQAAAAAAAgABAAIAAwMBBAMBAAAAAQAAAAAAAAAAAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAEGV4ZWN1dGVfc3RyYXRlZ3kAAAADAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAAKAAAAAAAAAAAAAAAABfXhAAAAAA0AAAFIAAAAEQAAAAEAAAADAAAADwAAAAdhbW91bnRzAAAAABAAAAABAAAAAQAAAAoAAAAAAAAAAAAAAAABWs8PAAAADwAAAAZhc3NldHMAAAAAABAAAAABAAAABQAAABIAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAASAAAAAWSckQ7ovqFqRdsVJt7plbpt1m0N+AmxVEbDpkeJUzkdAAAAEgAAAAE8+iVhwrKqEUvKWKDlZFP06ZwNGR1pFLzhZywtUHoQIQAAABIAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAASAAAAAWpw5ll0vKiNPB84WmsLQRrqyktm6GVb14MqgtAMsiwqAAAADwAAAANvcHMAAAAADQAAABQBAAEAAAAAAAIAAQACAAMDAQQDAQAAAAEAAAAAAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAACHRyYW5zZmVyAAAAAwAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAoAAAAAAAAAAAAAAAAF9eEAAAAAAAAAAAEAAAAAAAAADAAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAUAAAAAQAAAAYAAAABZJyRDui+oWpF2xUm3umVum3WbQ34CbFURsOmR4lTOR0AAAAUAAAAAQAAAAYAAAABanDmWXS8qI08HzhaawtBGurKS2boZVvXgyqC0AyyLCoAAAAQAAAAAQAAAAIAAAAPAAAAClRpY2tCaXRtYXAAAAAAAAQAAAAAAAAAAQAAAAYAAAABgBdpEMDtExocHiH9irvJRhjmZINGNLCz+nLu8EuXI4QAAAAUAAAAAQAAAAYAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAUAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAUAAAAAQAAAAYAAAAB9qiow41s+9Q7rddGQUy/r59DR974iuR8vdoGKlGsF9MAAAAUAAAAAQAAAAcANxCzg/nafWUKf3Gae+R5EQJmQngX677WHZJFBfzXxwAAAAcY63Zuh+1XiJKCjLuMFIF3Md2OVwzzhhdx+5RLhcNS6AAAAAdX5RCZSUyMhzE924baNMhV1kIxOHfPQiJBXn94RHIYeAAAAAeflMV36iTC9xy7DJZMnJ0yHgJEjR/pRgIK+xiXSxwmAgAAAAeuDaWoSxWAXFx5MaxWeo0bNL4/JrSDmT2f+Ayyw96YUgAAAAwAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAQAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAJVU0RUMAAAAAAAAAAAAAAAJole/g580X0KgHG/iSPknZXsWMptcgzeTVGOWDLyrpMAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABPPolYcKyqhFLylig5WRT9OmcDRkdaRS84WcsLVB6ECEAAAABAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABPPolYcKyqhFLylig5WRT9OmcDRkdaRS84WcsLVB6ECEAAAAUAAAAAQAAAAYAAAABZJyRDui+oWpF2xUm3umVum3WbQ34CbFURsOmR4lTOR0AAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAFqcOZZdLyojTwfOFprC0Ea6spLZuhlW9eDKoLQDLIsKgAAAAEAAAAGAAAAAWSckQ7ovqFqRdsVJt7plbpt1m0N+AmxVEbDpkeJUzkdAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAFqcOZZdLyojTwfOFprC0Ea6spLZuhlW9eDKoLQDLIsKgAAABQAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABAAAAABAAAAAgAAAA8AAAAIUG9vbERhdGEAAAASAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAE8+iVhwrKqEUvKWKDlZFP06ZwNGR1pFLzhZywtUHoQIQAAAAEAAAAGAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABanDmWXS8qI08HzhaawtBGurKS2boZVvXgyqC0AyyLCoAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQFHN+sAAAEMAAAYwAAAAAAAAV1FAAAAAfPRrNUAAABAg6M/f+4HKfL5g7GVJc9PYWnZMR79v7l9WJIoxIr7vmenqOCWYzp8SlNubIbcZuPZoa99qCcKcDhweCIioQlCAw==",
  },
} as unknown as Horizon.ServerApi.OperationRecord;

/** tx fbde9823: 1 PYUSD for 0.9953869 USDM1 through four pools; the changes list every hop, the user only the first debit and the last credit. */
export const pyusdToUsdm1MultiHop = {
  id: "277800889887887361",
  transaction_successful: true,
  source_account: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
  type: "invoke_host_function",
  type_i: 24,
  created_at: "2026-09-29T13:29:41Z",
  transaction_hash:
    "fbde9823e76b233440583da394b9e25abc59e282986868d37c0385028a7c7cda",
  asset_balance_changes: [
    {
      asset_type: "credit_alphanum12",
      asset_code: "PYUSD",
      asset_issuer: "GDQE7IXJ4HUHV6RQHIUPRJSEZE4DRS5WY577O2FY6YQ5LVWZ7JZTU2V5",
      type: "transfer",
      from: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "1.0000000",
    },
    {
      asset_type: "credit_alphanum12",
      asset_code: "PYUSD",
      asset_issuer: "GDQE7IXJ4HUHV6RQHIUPRJSEZE4DRS5WY577O2FY6YQ5LVWZ7JZTU2V5",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CB3ZWHICKIYJOSQ7W2GFN2U2CVSGTFBQ6GCDVGQ354BQYJCKX6L22CNH",
      amount: "1.0000000",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "AQUA",
      asset_issuer: "GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      type: "transfer",
      from: "CB3ZWHICKIYJOSQ7W2GFN2U2CVSGTFBQ6GCDVGQ354BQYJCKX6L22CNH",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "2630.2916545",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "AQUA",
      asset_issuer: "GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CDE57N6XTUPBKYYDGQMXX7E7SLNOLFY3JEQB4MULSMR2AKTSAENGX2HC",
      amount: "2630.2916545",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CDE57N6XTUPBKYYDGQMXX7E7SLNOLFY3JEQB4MULSMR2AKTSAENGX2HC",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "4.3033236",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CA6PUJLBYKZKUEKLZJMKBZLEKP2OTHANDEOWSFF44FTSYLKQPIICCJBE",
      amount: "4.3033236",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CA6PUJLBYKZKUEKLZJMKBZLEKP2OTHANDEOWSFF44FTSYLKQPIICCJBE",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "1.0003569",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CCJ3XJR5VODGJHH6BQHRUVOA3FWMQRQOPLUZNKLSKFKYELZF767P2DOR",
      amount: "1.0003569",
    },
    {
      asset_type: "credit_alphanum12",
      asset_code: "USDM1",
      asset_issuer: "GDM5QWWXCMDTQMZAKMYTCI52LA7FWBHAZMU5NJLMIFHDJISJRP2ZWPKC",
      type: "transfer",
      from: "CCJ3XJR5VODGJHH6BQHRUVOA3FWMQRQOPLUZNKLSKFKYELZF767P2DOR",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.9953869",
    },
    {
      asset_type: "credit_alphanum12",
      asset_code: "USDM1",
      asset_issuer: "GDM5QWWXCMDTQMZAKMYTCI52LA7FWBHAZMU5NJLMIFHDJISJRP2ZWPKC",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
      amount: "0.9953869",
    },
  ],
  transaction_attr: {
    fee_charged: "2099821",
    operation_count: 1,
    envelope_xdr:
      "AAAAAgAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAkvVoDsoV+AAAAfAAAAAEAAAAAAAAAAAAAAABqu73pAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQZXhlY3V0ZV9zdHJhdGVneQAAAAMAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAoAAAAAAAAAAAAAAAAAmJaAAAAADQAAAfQAAAARAAAAAQAAAAMAAAAPAAAAB2Ftb3VudHMAAAAAEAAAAAEAAAABAAAACgAAAAAAAAAAAAAAAACU6eUAAAAPAAAABmFzc2V0cwAAAAAAEAAAAAEAAAAJAAAAEgAAAAGFGx/Q2Vr9o0jvwjWzoCgn93nF8ZUHC9KSWjBWOe/k8wAAABIAAAABBf5tuIhZL/l6GJ4L5m4hfES9T6kF119Svj53WbdEpLoAAAASAAAAAXebHQJSMJdKH7aMVuqaFWRplDDxhDqaG+8DDCRKv5etAAAAEgAAAAEohS9owZhIjjRvsSEu1QKQU3Ycwk9FM5LjU5ggGwgl5wAAABIAAAAByd+3150eFWMDNBl7/J+S2uWXG0kgHjKLkyOgKnIBGmsAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEgAAAAE8+iVhwrKqEUvKWKDlZFP06ZwNGR1pFLzhZywtUHoQIQAAABIAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAASAAAAAZO7pj2rhmSc/gwPGlXA2WzIRg566ZapclFVgi8l/779AAAADwAAAANvcHMAAAAADQAAAB4BAAEAAAAAAAQAAQACAAMBAQQDBQEBBgUHAQEIBwEAAAAAAAEAAAAAAAAAAAAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAABBleGVjdXRlX3N0cmF0ZWd5AAAAAwAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAACgAAAAAAAAAAAAAAAACYloAAAAANAAAB9AAAABEAAAABAAAAAwAAAA8AAAAHYW1vdW50cwAAAAAQAAAAAQAAAAEAAAAKAAAAAAAAAAAAAAAAAJTp5QAAAA8AAAAGYXNzZXRzAAAAAAAQAAAAAQAAAAkAAAASAAAAAYUbH9DZWv2jSO/CNbOgKCf3ecXxlQcL0pJaMFY57+TzAAAAEgAAAAEF/m24iFkv+XoYngvmbiF8RL1PqQXXX1K+PndZt0SkugAAABIAAAABd5sdAlIwl0oftoxW6poVZGmUMPGEOpob7wMMJEq/l60AAAASAAAAASiFL2jBmEiONG+xIS7VApBTdhzCT0UzkuNTmCAbCCXnAAAAEgAAAAHJ37fXnR4VYwM0GXv8n5La5ZcbSSAeMouTI6AqcgEaawAAABIAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAASAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABIAAAABk7umPauGZJz+DA8aVcDZbMhGDnrplqlyUVWCLyX/vv0AAAAPAAAAA29wcwAAAAANAAAAHgEAAQAAAAAABAABAAIAAwEBBAMFAQEGBQcBAQgHAQAAAAAAAQAAAAAAAAABhRsf0Nla/aNI78I1s6AoJ/d5xfGVBwvSklowVjnv5PMAAAAIdHJhbnNmZXIAAAADAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAACgAAAAAAAAAAAAAAAACYloAAAAAAAAAAAQAAAAAAAAANAAAAAAAAAADZ2FrXEwc4MyBTMTEjulg+WwTgyynWpWxBTjSiSYv1mwAAAAYAAAABBf5tuIhZL/l6GJ4L5m4hfES9T6kF119Svj53WbdEpLoAAAAUAAAAAQAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAUAAAAAQAAAAYAAAABKIUvaMGYSI40b7EhLtUCkFN2HMJPRTOS41OYIBsIJecAAAAUAAAAAQAAAAYAAAABd5sdAlIwl0oftoxW6poVZGmUMPGEOpob7wMMJEq/l60AAAAQAAAAAQAAAAIAAAAPAAAACVRpY2tDaHVuawAAAAAAAAT///8JAAAAAQAAAAYAAAABgBdpEMDtExocHiH9irvJRhjmZINGNLCz+nLu8EuXI4QAAAAUAAAAAQAAAAYAAAABhRsf0Nla/aNI78I1s6AoJ/d5xfGVBwvSklowVjnv5PMAAAAUAAAAAQAAAAYAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAUAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAUAAAAAQAAAAcS/KWnqWV3JzttQYTPnJhANs2g6PBZR0fnspM9ztN+5gAAAAcY63Zuh+1XiJKCjLuMFIF3Md2OVwzzhhdx+5RLhcNS6AAAAAdX5RCZSUyMhzE924baNMhV1kIxOHfPQiJBXn94RHIYeAAAAAeuDaWoSxWAXFx5MaxWeo0bNL4/JrSDmT2f+Ayyw96YUgAAABYAAAABAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAlBZVVNEAAAAAAAAAAAAAADgT6Lp4eh6+jA6KPimRMk4OMu2x3/3aLj2IdXW2fpzOgAAAAEAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAACVVNETTEAAAAAAAAAAAAAANnYWtcTBzgzIFMxMSO6WD5bBODLKdalbEFONKJJi/WbAAAABgAAAAEF/m24iFkv+XoYngvmbiF8RL1PqQXXX1K+PndZt0SkugAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAZO7pj2rhmSc/gwPGlXA2WzIRg566ZapclFVgi8l/779AAAAAQAAAAYAAAABBf5tuIhZL/l6GJ4L5m4hfES9T6kF119Svj53WbdEpLoAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABPPolYcKyqhFLylig5WRT9OmcDRkdaRS84WcsLVB6ECEAAAABAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAHJ37fXnR4VYwM0GXv8n5La5ZcbSSAeMouTI6AqcgEaawAAAAEAAAAGAAAAASiFL2jBmEiONG+xIS7VApBTdhzCT0UzkuNTmCAbCCXnAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABd5sdAlIwl0oftoxW6poVZGmUMPGEOpob7wMMJEq/l60AAAABAAAABgAAAAEohS9owZhIjjRvsSEu1QKQU3Ycwk9FM5LjU5ggGwgl5wAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABKIUvaMGYSI40b7EhLtUCkFN2HMJPRTOS41OYIBsIJecAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAHJ37fXnR4VYwM0GXv8n5La5ZcbSSAeMouTI6AqcgEaawAAAAEAAAAGAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAAFAAAAAEAAAAGAAAAAXebHQJSMJdKH7aMVuqaFWRplDDxhDqaG+8DDCRKv5etAAAAFAAAAAEAAAAGAAAAAYAXaRDA7RMaHB4h/Yq7yUYY5mSDRjSws/py7vBLlyOEAAAAEAAAAAEAAAACAAAADwAAAAhQb29sRGF0YQAAABIAAAABPPolYcKyqhFLylig5WRT9OmcDRkdaRS84WcsLVB6ECEAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABAAAAABAAAAAgAAAA8AAAAIUG9vbERhdGEAAAASAAAAAZO7pj2rhmSc/gwPGlXA2WzIRg566ZapclFVgi8l/779AAAAAQAAAAYAAAABgBdpEMDtExocHiH9irvJRhjmZINGNLCz+nLu8EuXI4QAAAAQAAAAAQAAAAIAAAAPAAAACFBvb2xEYXRhAAAAEgAAAAHJ37fXnR4VYwM0GXv8n5La5ZcbSSAeMouTI6AqcgEaawAAAAEAAAAGAAAAAYUbH9DZWv2jSO/CNbOgKCf3ecXxlQcL0pJaMFY57+TzAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABd5sdAlIwl0oftoxW6poVZGmUMPGEOpob7wMMJEq/l60AAAABAAAABgAAAAGFGx/Q2Vr9o0jvwjWzoCgn93nF8ZUHC9KSWjBWOe/k8wAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABk7umPauGZJz+DA8aVcDZbMhGDnrplqlyUVWCLyX/vv0AAAAUAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAE8+iVhwrKqEUvKWKDlZFP06ZwNGR1pFLzhZywtUHoQIQAAAAEAAAAGAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABk7umPauGZJz+DA8aVcDZbMhGDnrplqlyUVWCLyX/vv0AAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAAByd+3150eFWMDNBl7/J+S2uWXG0kgHjKLkyOgKnIBGmsAAAAUAAAAAQHazIsAAAGIAAA2RAAAAAAAJLz2AAAAAfPRrNUAAABAib5587Lxy+A29zXMRaa0SONKPKL243VtxDoxszZznLcBDSG7xjVGTkDDXR3OpbqxkK2CAnZyOP0cKcf9r5KbDQ==",
  },
} as unknown as Horizon.ServerApi.OperationRecord;

/** tx efb32c1f: 6.7546053 USDC for XAUM, a Soroban token. The balance changes hold only the debit; the credit is in the transaction's events (`usdcToXaumMeta`). */
export const usdcToXaum = {
  id: "277803200580513793",
  transaction_successful: true,
  source_account: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
  type: "invoke_host_function",
  type_i: 24,
  created_at: "2026-09-29T14:14:31Z",
  transaction_hash:
    "efb32c1f49feb2484188f5371b02c4dfd15c912d2d749f5fd7120afe4134517e",
  asset_balance_changes: [
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "6.7546053",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CA6PUJLBYKZKUEKLZJMKBZLEKP2OTHANDEOWSFF44FTSYLKQPIICCJBE",
      amount: "6.7546053",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CA6PUJLBYKZKUEKLZJMKBZLEKP2OTHANDEOWSFF44FTSYLKQPIICCJBE",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "29.2748691",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CBISULYO5ZGS32WTNCBMEFCNKNSLFXCQ4Z3XHVDP4X4FLPSEALGSY3PS",
      amount: "29.2748691",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "EURC",
      asset_issuer: "GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2",
      type: "transfer",
      from: "CBISULYO5ZGS32WTNCBMEFCNKNSLFXCQ4Z3XHVDP4X4FLPSEALGSY3PS",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "5.9784011",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "EURC",
      asset_issuer: "GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2",
      type: "transfer",
      from: "CBISULYO5ZGS32WTNCBMEFCNKNSLFXCQ4Z3XHVDP4X4FLPSEALGSY3PS",
      to: "GA2N5NZL2IGVH7FWGBHOZNXRZL2XFHLYIFXC5XGU2COUMQCK7MAJUXXV",
      amount: "0.0300422",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "EURC",
      asset_issuer: "GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CCPN4NNSQKL3LLPTSPTFKYKXR3FBL37AULE6PTZH3QD24MPHXQCN5O3U",
      amount: "5.9784011",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "sUSD",
      asset_issuer: "GCHW7CWI7GMIYQYFXMFJNJX5645XGWIINIAEQK3SABQO6CAYL5T7JYIH",
      type: "transfer",
      from: "CCPN4NNSQKL3LLPTSPTFKYKXR3FBL37AULE6PTZH3QD24MPHXQCN5O3U",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "6.7690491",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "sUSD",
      asset_issuer: "GCHW7CWI7GMIYQYFXMFJNJX5645XGWIINIAEQK3SABQO6CAYL5T7JYIH",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CA4HVQTVHQWDIZSQQQBXYHCA4C5D6V2ZGRHJQIKHVDMBEXCMFH4NYURR",
      amount: "6.7690491",
    },
  ],
  transaction_attr: {
    fee_charged: "386915",
    operation_count: 1,
    envelope_xdr:
      "AAAAAgAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAGr8wDsoV+AAAAfQAAAAEAAAAAAAAAAAAAAABqu8hUAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQZXhlY3V0ZV9zdHJhdGVneQAAAAMAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAoAAAAAAAAAAAAAAAAEBqvFAAAADQAAAfQAAAARAAAAAQAAAAMAAAAPAAAAB2Ftb3VudHMAAAAAEAAAAAEAAAABAAAACgAAAAAAAAAAAAAAAAAYKtYAAAAPAAAABmFzc2V0cwAAAAAAEAAAAAEAAAAJAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABIAAAABtRCbDRFCKpGoGvoShs8/HUyzVAbcPStN7wy2WELirPoAAAASAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABIAAAABUSovDu5NLerTaILCFE1TZLLcUOZ3c9Rv5fhVvkQCzSwAAAASAAAAAean2et1IwBqRpqnSDrREHJHRDwNguYnY95nCEjE6XyQAAAAEgAAAAGe3jWygpe1rfOT5lVhV47KFe/gosnnzyfcB64x57wE3gAAABIAAAABy5pWXcNXen6kap1BkccSTKg2tA2H9TG+J/MXKfh5VxoAAAASAAAAATh6wnU8LDRmUIQDfBxA4Lo/V1k0TpghR6jYElxMKfjcAAAADwAAAANvcHMAAAAADQAAAB4BAAEAAAAAAAQAAQACAAMCAQQDBQEBBgUHAQEIBwEAAAAAAAEAAAAAAAAAAAAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAABBleGVjdXRlX3N0cmF0ZWd5AAAAAwAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAACgAAAAAAAAAAAAAAAAQGq8UAAAANAAAB9AAAABEAAAABAAAAAwAAAA8AAAAHYW1vdW50cwAAAAAQAAAAAQAAAAEAAAAKAAAAAAAAAAAAAAAAABgq1gAAAA8AAAAGYXNzZXRzAAAAAAAQAAAAAQAAAAkAAAASAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEgAAAAG1EJsNEUIqkaga+hKGzz8dTLNUBtw9K03vDLZYQuKs+gAAABIAAAABPPolYcKyqhFLylig5WRT9OmcDRkdaRS84WcsLVB6ECEAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAABIAAAAB5qfZ63UjAGpGmqdIOtEQckdEPA2C5idj3mcISMTpfJAAAAASAAAAAZ7eNbKCl7Wt85PmVWFXjsoV7+CiyefPJ9wHrjHnvATeAAAAEgAAAAHLmlZdw1d6fqRqnUGRxxJMqDa0DYf1Mb4n8xcp+HlXGgAAABIAAAABOHrCdTwsNGZQhAN8HEDguj9XWTROmCFHqNgSXEwp+NwAAAAPAAAAA29wcwAAAAANAAAAHgEAAQAAAAAABAABAAIAAwIBBAMFAQEGBQcBAQgHAQAAAAAAAQAAAAAAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAIdHJhbnNmZXIAAAADAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAACgAAAAAAAAAAAAAAAAQGq8UAAAAAAAAAAQAAAAAAAAAVAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABQAAAABAAAABgAAAAE4esJ1PCw0ZlCEA3wcQOC6P1dZNE6YIUeo2BJcTCn43AAAABAAAAABAAAAAgAAAA8AAAALQ2h1bmtCaXRtYXAAAAAABAAAAAAAAAABAAAABgAAAAE4esJ1PCw0ZlCEA3wcQOC6P1dZNE6YIUeo2BJcTCn43AAAABAAAAABAAAAAgAAAA8AAAAJVGlja0NodW5rAAAAAAAABAAAAHQAAAABAAAABgAAAAE4esJ1PCw0ZlCEA3wcQOC6P1dZNE6YIUeo2BJcTCn43AAAABAAAAABAAAAAgAAAA8AAAAJVGlja0NodW5rAAAAAAAABAAAAHUAAAABAAAABgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAAA8AAAAGQ09ORklHAAAAAAABAAAABgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAABQAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABQAAAABAAAABgAAAAGe3jWygpe1rfOT5lVhV47KFe/gosnnzyfcB64x57wE3gAAABAAAAABAAAAAgAAAA8AAAAJVGlja0NodW5rAAAAAAAABP////wAAAABAAAABgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAABQAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABQAAAABAAAABgAAAAG1EJsNEUIqkaga+hKGzz8dTLNUBtw9K03vDLZYQuKs+gAAABAAAAABAAAAAgAAAA8AAAAHQmxvY2tlZAAAAAASAAAAATh6wnU8LDRmUIQDfBxA4Lo/V1k0TpghR6jYElxMKfjcAAAAAQAAAAYAAAABtRCbDRFCKpGoGvoShs8/HUyzVAbcPStN7wy2WELirPoAAAAQAAAAAQAAAAIAAAAPAAAAB0Jsb2NrZWQAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAbUQmw0RQiqRqBr6EobPPx1Ms1QG3D0rTe8MtlhC4qz6AAAAFAAAAAEAAAAGAAAAAcuaVl3DV3p+pGqdQZHHEkyoNrQNh/UxvifzFyn4eVcaAAAAFAAAAAEAAAAGAAAAAean2et1IwBqRpqnSDrREHJHRDwNguYnY95nCEjE6XyQAAAAFAAAAAEAAAAHEvylp6lldyc7bUGEz5yYQDbNoOjwWUdH57KTPc7TfuYAAAAHFnq0FKImQn3jTBmUfvnFzzjGwO2R7Pk5L3zvMnj/UGwAAAAHGOt2boftV4iSgoy7jBSBdzHdjlcM84YXcfuUS4XDUugAAAAHL5GnDRqQZz4oBkTgSJkjhY0TXaszD7XvjjLmQCnsq90AAAAHV+UQmUlMjIcxPduG2jTIVdZCMTh3z0IiQV5/eERyGHgAAAAHrg2lqEsVgFxceTGsVnqNGzS+Pya0g5k9n/gMssPemFIAAAAWAAAAAQAAAAA03rcr0g1T/LYwTuy28cr1cp14QW4u3NTQnUZASvsAmgAAAAFFVVJDAAAAAM9PWibiCQuzrc8Cx6nXPb/mZZzGkEYUdbhkN/pJxxE2AAAAAQAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAAAQAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAAAEAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAE4esJ1PCw0ZlCEA3wcQOC6P1dZNE6YIUeo2BJcTCn43AAAABQAAAABAAAABgAAAAE8+iVhwrKqEUvKWKDlZFP06ZwNGR1pFLzhZywtUHoQIQAAABQAAAABAAAABgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAAAMAAAABAAAAAQAAAAYAAAABUSovDu5NLerTaILCFE1TZLLcUOZ3c9Rv5fhVvkQCzSwAAAADAAAAAgAAAAEAAAAGAAAAAYAXaRDA7RMaHB4h/Yq7yUYY5mSDRjSws/py7vBLlyOEAAAAEAAAAAEAAAACAAAADwAAAAhQb29sRGF0YQAAABIAAAABPPolYcKyqhFLylig5WRT9OmcDRkdaRS84WcsLVB6ECEAAAABAAAABgAAAAGe3jWygpe1rfOT5lVhV47KFe/gosnnzyfcB64x57wE3gAAABQAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAbUQmw0RQiqRqBr6EobPPx1Ms1QG3D0rTe8MtlhC4qz6AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAQAAAAYAAAABtRCbDRFCKpGoGvoShs8/HUyzVAbcPStN7wy2WELirPoAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAE4esJ1PCw0ZlCEA3wcQOC6P1dZNE6YIUeo2BJcTCn43AAAAAEAAAAGAAAAAbUQmw0RQiqRqBr6EobPPx1Ms1QG3D0rTe8MtlhC4qz6AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAHLmlZdw1d6fqRqnUGRxxJMqDa0DYf1Mb4n8xcp+HlXGgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAATh6wnU8LDRmUIQDfBxA4Lo/V1k0TpghR6jYElxMKfjcAAAAAQAAAAYAAAABy5pWXcNXen6kap1BkccSTKg2tA2H9TG+J/MXKfh5VxoAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGe3jWygpe1rfOT5lVhV47KFe/gosnnzyfcB64x57wE3gAAAAEAAAAGAAAAAcuaVl3DV3p+pGqdQZHHEkyoNrQNh/UxvifzFyn4eVcaAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAHmp9nrdSMAakaap0g60RByR0Q8DYLmJ2PeZwhIxOl8kAAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAVEqLw7uTS3q02iCwhRNU2Sy3FDmd3PUb+X4Vb5EAs0sAAAAAQAAAAYAAAAB5qfZ63UjAGpGmqdIOtEQckdEPA2C5idj3mcISMTpfJAAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGe3jWygpe1rfOT5lVhV47KFe/gosnnzyfcB64x57wE3gAAAAEAAAAGAAAAAean2et1IwBqRpqnSDrREHJHRDwNguYnY95nCEjE6XyQAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAfhonAAAAOgAACtUAAAAAAAGr2gAAAAB89Gs1QAAAEDpcv6Mc/s+/MiUR3AWyz+7Rsvdu8NhfLpX3etpzA08dWQL2O9n041eUOz+x9/LWWxcDHJDQSVKzDhVIniti3MC",
  },
} as unknown as Horizon.ServerApi.OperationRecord;

/** tx 00b48fc5 (2026-09-16): 2 XLM for a Soroban pool share token. Only the debit is in the balance changes. */
export const xlmToSorobanPoolShare = {
  id: "276859274143027201",
  transaction_successful: true,
  source_account: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
  type: "invoke_host_function",
  type_i: 24,
  created_at: "2026-09-16T20:59:51Z",
  transaction_hash:
    "00b48fc5434242a692424bb0ba29aad0ef74f7410a899dc74a0c6d72b9c8c9ad",
  asset_balance_changes: [
    {
      asset_type: "native",
      type: "transfer",
      from: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "2.0000000",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CD2A3X2D5ITHYA4DQ5TANYWAUAUP4G5QCMQILCMKXCXSR76OGNIC3C6N",
      amount: "2.0000000",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "XAU",
      asset_issuer: "GBCB4WO6J4ET55RWK2SVX76LUQ4PQ7TCDHG2YFILQML7D6XR3HACLXAU",
      type: "transfer",
      from: "CD2A3X2D5ITHYA4DQ5TANYWAUAUP4G5QCMQILCMKXCXSR76OGNIC3C6N",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "157706.0959068",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "XAU",
      asset_issuer: "GBCB4WO6J4ET55RWK2SVX76LUQ4PQ7TCDHG2YFILQML7D6XR3HACLXAU",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CB6E2TJAPMALVDDAJ4IM3MLRSXDO73YEH636SRZXYWLVMZSCA4THDMYI",
      amount: "157706.0959068",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CB6E2TJAPMALVDDAJ4IM3MLRSXDO73YEH636SRZXYWLVMZSCA4THDMYI",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.3681601",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      amount: "0.1841720",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDY",
      asset_issuer: "GAJMPX5NBOG6TQFPQGRABJEEB2YE7RFRLUKJDZAZGAD5GFX4J7TADAZ6",
      type: "transfer",
      from: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.1625627",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDY",
      asset_issuer: "GAJMPX5NBOG6TQFPQGRABJEEB2YE7RFRLUKJDZAZGAD5GFX4J7TADAZ6",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      amount: "0.1625627",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      amount: "0.1839881",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.0000003",
    },
  ],
  transaction_attr: {
    fee_charged: "1581337",
    operation_count: 1,
    envelope_xdr:
      "AAAAAgAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAdJ8IDsoV+AAAAbAAAAAEAAAAAAAAAAAAAAABqqwRrAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQZXhlY3V0ZV9zdHJhdGVneQAAAAMAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAoAAAAAAAAAAAAAAAABMS0AAAAADQAAAeQAAAARAAAAAQAAAAMAAAAPAAAAB2Ftb3VudHMAAAAAEAAAAAEAAAACAAAACgAAAAAAAAAAAAAAAAAaQTQAAAAKAAAAAAAAAAAAAAAAABpBMwAAAA8AAAAGYXNzZXRzAAAAAAAQAAAAAQAAAAgAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEgAAAAGwPgtWLZCBl1vshDuSy+xn6Xd2hZYz0nDtJZ7VpetOkwAAABIAAAAB9A3fQ+omfAODh2YG4sCgKP4bsBMghYmKuK8o/84zUC0AAAASAAAAAbtLgNl1NfdAKg4nBhJbbV3iV8UTLSa95wPRL0tcI1mxAAAAEgAAAAF8TU0gewC6jGBPEM2xcZXG7+8EP7fpRzfFl1ZmQgcmcQAAABIAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAASAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAEgAAAAF3gHu+dhB6d/7v0dUaQYnJ1G3ZpypRa0/AHAaXJyWbgwAAAA8AAAADb3BzAAAAAA0AAAAhAQABAAAAAAAEAQAAAgADAQEEAwUBgAYFBwYABgEBB6IaAAAAAAAAAQAAAAAAAAAAAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAEGV4ZWN1dGVfc3RyYXRlZ3kAAAADAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAAKAAAAAAAAAAAAAAAAATEtAAAAAA0AAAHkAAAAEQAAAAEAAAADAAAADwAAAAdhbW91bnRzAAAAABAAAAABAAAAAgAAAAoAAAAAAAAAAAAAAAAAGkE0AAAACgAAAAAAAAAAAAAAAAAaQTMAAAAPAAAABmFzc2V0cwAAAAAAEAAAAAEAAAAIAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABIAAAABsD4LVi2QgZdb7IQ7ksvsZ+l3doWWM9Jw7SWe1aXrTpMAAAASAAAAAfQN30PqJnwDg4dmBuLAoCj+G7ATIIWJirivKP/OM1AtAAAAEgAAAAG7S4DZdTX3QCoOJwYSW21d4lfFEy0mvecD0S9LXCNZsQAAABIAAAABfE1NIHsAuoxgTxDNsXGVxu/vBD+36Uc3xZdWZkIHJnEAAAASAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEgAAAAEKdZzZu6rRGKn43XX9I2sCImVDRtcutjA+zXF8UkMhkwAAABIAAAABd4B7vnYQenf+79HVGkGJydRt2acqUWtPwBwGlyclm4MAAAAPAAAAA29wcwAAAAANAAAAIQEAAQAAAAAABAEAAAIAAwEBBAMFAYAGBQcGAAYBAQeiGgAAAAAAAAEAAAAAAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAACHRyYW5zZmVyAAAAAwAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAoAAAAAAAAAAAAAAAABMS0AAAAAAAAAAAEAAAAAAAAAFAAAAAEAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAABSUNFAAAAAAAvI2dJZtbbOdy0TAGiTWWdw8Fm5AJqZio/cnXskAmv/QAAAAYAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAAQAAAAAQAAAAIAAAAPAAAADlVzZXJSZXdhcmREYXRhAAAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAAQAAAAAQAAAAIAAAAPAAAAEFVzZXJSZXdhcmRzU3RhdGUAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAEAAAAGAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAEAAAAAEAAAACAAAADwAAABBVc2VyUmV3YXJkc1N0YXRlAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAASIlZ96nAI13nWy5EBefhUlzbfGIhg7o/IbKOIDSY/gYAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAEiJWfepwCNd51suRAXn4VJc23xiIYO6PyGyjiA0mP4GAAAABQAAAABAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABQAAAABAAAABgAAAAFUKLid9OmiznsXRVb7/n4quboUgM5z9+Zdh47VypCy8wAAABQAAAABAAAABgAAAAF3gHu+dhB6d/7v0dUaQYnJ1G3ZpypRa0/AHAaXJyWbgwAAABQAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABQAAAABAAAABgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAABQAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABQAAAABAAAABgAAAAGwPgtWLZCBl1vshDuSy+xn6Xd2hZYz0nDtJZ7VpetOkwAAABQAAAABAAAABgAAAAG7S4DZdTX3QCoOJwYSW21d4lfFEy0mvecD0S9LXCNZsQAAABQAAAABAAAABwe6sw65P50ZSweaPwK6hoIa6CudR3CjjGt7hSTfnihPAAAABxgFFFaBa2bxLnc6Vvd8V5T6wbH7erbiLU+tWkEncPc+AAAAB1flEJlJTIyHMT3bhto0yFXWQjE4d89CIkFef3hEchh4AAAAB4Jfx9e7rnJgcACngSZGTIF8R/+az0Pn1vqpYzTvvG5NAAAAB41Yu8WJc5iIphqAQJAhXsOH5kKjZ9wBs018nRP+NBYEAAAAB64NpahLFYBcXHkxrFZ6jRs0vj8mtIOZPZ/4DLLD3phSAAAAFwAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAAGAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAEAAAAAEAAAACAAAADwAAAA5Vc2VyUmV3YXJkRGF0YQAAAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAABAAAABgAAAAEKdZzZu6rRGKn43XX9I2sCImVDRtcutjA+zXF8UkMhkwAAABAAAAABAAAAAgAAAA8AAAAOV29ya2luZ0JhbGFuY2UAAAAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAQAAAAYAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAAQAAAAAQAAAAIAAAAPAAAADldvcmtpbmdCYWxhbmNlAAAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAAUAAAAAQAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAAB9A3fQ+omfAODh2YG4sCgKP4bsBMghYmKuK8o/84zUC0AAAABAAAABgAAAAF3gHu+dhB6d/7v0dUaQYnJ1G3ZpypRa0/AHAaXJyWbgwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAAQAAAAYAAAABd4B7vnYQenf+79HVGkGJydRt2acqUWtPwBwGlyclm4MAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAXxNTSB7ALqMYE8QzbFxlcbv7wQ/t+lHN8WXVmZCByZxAAAAFAAAAAEAAAAGAAAAAYAXaRDA7RMaHB4h/Yq7yUYY5mSDRjSws/py7vBLlyOEAAAAEAAAAAEAAAACAAAADwAAAAhQb29sRGF0YQAAABIAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABAAAAABAAAAAgAAAA8AAAAIUG9vbERhdGEAAAASAAAAAXxNTSB7ALqMYE8QzbFxlcbv7wQ/t+lHN8WXVmZCByZxAAAAAQAAAAYAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQAAAAAQAAAAIAAAAPAAAACEFkbWluRmVlAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAAAEAAAAGAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAEAAAAAEAAAACAAAADwAAAA1SZXNlcnZlZFRvdGFsAAAAAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAAAEAAAAGAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAXxNTSB7ALqMYE8QzbFxlcbv7wQ/t+lHN8WXVmZCByZxAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAbA+C1YtkIGXW+yEO5LL7Gfpd3aFljPScO0lntWl606TAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAQAAAAYAAAABsD4LVi2QgZdb7IQ7ksvsZ+l3doWWM9Jw7SWe1aXrTpMAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAbtLgNl1NfdAKg4nBhJbbV3iV8UTLSa95wPRL0tcI1mxAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABfE1NIHsAuoxgTxDNsXGVxu/vBD+36Uc3xZdWZkIHJnEAAAABAAAABgAAAAG7S4DZdTX3QCoOJwYSW21d4lfFEy0mvecD0S9LXCNZsQAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABu0uA2XU190AqDicGElttXeJXxRMtJr3nA9EvS1wjWbEAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAH0Dd9D6iZ8A4OHZgbiwKAo/huwEyCFiYq4ryj/zjNQLQAAAAEAAAAGAAAAAfQN30PqJnwDg4dmBuLAoCj+G7ATIIWJirivKP/OM1AtAAAAFAAAAAECcmdhAAAAkAAAIwgAAAAAABuhIgAAAAHz0azVAAAAQClKE7HK1iRvsUU4Q0hXiseqox/240WD9py9OGGVQrFDqIA823Rtzj59OnxQv8SWhK+/rJPF9cd6n95EhJLUEA8=",
  },
} as unknown as Horizon.ServerApi.OperationRecord;

/** tx ba19d3bf (2026-09-16): a Soroban token for another. The balance changes are empty: both legs are Soroban tokens. */
export const sorobanToSoroban = {
  id: "276859566200434689",
  transaction_successful: true,
  source_account: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
  type: "invoke_host_function",
  type_i: 24,
  created_at: "2026-09-16T21:05:31Z",
  transaction_hash:
    "ba19d3bf93ce26b1eac2de35aa34f54d39de2afa1c561fc7657003fa8b0c669b",
  asset_balance_changes: [
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDY",
      asset_issuer: "GAJMPX5NBOG6TQFPQGRABJEEB2YE7RFRLUKJDZAZGAD5GFX4J7TADAZ6",
      type: "transfer",
      from: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.1625625",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.1839876",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      amount: "0.1839876",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDY",
      asset_issuer: "GAJMPX5NBOG6TQFPQGRABJEEB2YE7RFRLUKJDZAZGAD5GFX4J7TADAZ6",
      type: "transfer",
      from: "CAFHLHGZXOVNCGFJ7DOXL7JDNMBCEZKDI3LS5NRQH3GXC7CSIMQZHUSM",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.1623999",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDY",
      asset_issuer: "GAJMPX5NBOG6TQFPQGRABJEEB2YE7RFRLUKJDZAZGAD5GFX4J7TADAZ6",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CA75VVHLWSM7W6ULNQI7ZJYDFOMQCCPKIDDDHBAL5KOKHWWKWQ5S7MHO",
      amount: "0.3249624",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CA75VVHLWSM7W6ULNQI7ZJYDFOMQCCPKIDDDHBAL5KOKHWWKWQ5S7MHO",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "0.3674369",
    },
    {
      asset_type: "credit_alphanum4",
      asset_code: "USDC",
      asset_issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CBXCELPGAJPHC4XXYBOYLWNLH2IZBUNNXCR4IIBNJXL6BSVTHSLAOJYP",
      amount: "0.3674369",
    },
    {
      asset_type: "credit_alphanum12",
      asset_code: "LIBRE",
      asset_issuer: "GAYCCWKECNGDRHYU3UTREBD2XLC3CUQN6FV22TKM4WCQER3IWR7TF5CY",
      type: "transfer",
      from: "CBXCELPGAJPHC4XXYBOYLWNLH2IZBUNNXCR4IIBNJXL6BSVTHSLAOJYP",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "351.9171770",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CAKWXQDEVVUF2ABUEM3M2G7QJGJNDZNNVXJZYG4Z4QP6K54QTWV4DW2S",
      to: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      amount: "2.0224032",
    },
    {
      asset_type: "credit_alphanum12",
      asset_code: "LIBRE",
      asset_issuer: "GAYCCWKECNGDRHYU3UTREBD2XLC3CUQN6FV22TKM4WCQER3IWR7TF5CY",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CAKWXQDEVVUF2ABUEM3M2G7QJGJNDZNNVXJZYG4Z4QP6K54QTWV4DW2S",
      amount: "351.9171770",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CD2O2B6PWKXDVFXMHXHQMF25C4TWOSQAENA7DNFR5G27F5CHJ7AJP5F6",
      amount: "1.0133291",
    },
    {
      asset_type: "native",
      type: "transfer",
      from: "CCVENFSVCBYDHVOACFZXMNNYVOZ3LKXPZYU5LUI4N7KTXOKRVYD7F3TR",
      to: "CD2O2B6PWKXDVFXMHXHQMF25C4TWOSQAENA7DNFR5G27F5CHJ7AJP5F6",
      amount: "1.0090741",
    },
  ],
  transaction_attr: {
    fee_charged: "5133273",
    operation_count: 1,
    envelope_xdr:
      "AAAAAgAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QBbN1cDsoV+AAAAbwAAAAEAAAAAAAAAAAAAAABqqwW7AAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQZXhlY3V0ZV9zdHJhdGVneQAAAAMAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAoAAAAAAAAAAAAAAAAAGmL6AAAADQAAArgAAAARAAAAAQAAAAMAAAAPAAAAB2Ftb3VudHMAAAAAEAAAAAEAAAAEAAAACgAAAAAAAAAAAAAAAAAAvxgAAAAKAAAAAAAAAAAAAAAAABiuWAAAAAoAAAAAAAAAAAAAAAAAG+8UAAAACgAAAAAAAAAAAAAAAAAAvxgAAAAPAAAABmFzc2V0cwAAAAAAEAAAAAEAAAAMAAAAEgAAAAGwPgtWLZCBl1vshDuSy+xn6Xd2hZYz0nDtJZ7VpetOkwAAABIAAAABHvXvjS+v9myQKh475PC+nz2RxNLwIbon28ulziORTWoAAAASAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABIAAAABd4B7vnYQenf+79HVGkGJydRt2acqUWtPwBwGlyclm4MAAAASAAAAAT/a1Ou0mft6i2wR/KcDK5kBCepAxjOEC+qco9rKtDsvAAAAEgAAAAFuIi3mAl5xcvfAXYXZqz6RkNGtuKPEIC1N1+DKszyWBwAAABIAAAABSM0ICMLZs4XPp064L/XoaAUzbf/HiCr8K084LhSg9ZIAAAASAAAAARVrwGStaF0ANCM2zRvwSZLR5a2t05wbmeQf5XeQnavBAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABIAAAAB9O0Hz7KuOpbsPc8GF10XJ2dKACNB8bSx6bXy9EdPwJcAAAASAAAAAVCQjblpeX30KeFLmwhhkJTn9aHj1m5JpGxYsD8G4/pWAAAADwAAAANvcHMAAAAADQAAADABAAEAAAAAAAcBBQACAAEBAAIDBAMABQQDAQEGAwcDAQgHCQGACgkLBgAKAQMHpTwAAAABAAAAAAAAAAAAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAQZXhlY3V0ZV9zdHJhdGVneQAAAAMAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAoAAAAAAAAAAAAAAAAAGmL6AAAADQAAArgAAAARAAAAAQAAAAMAAAAPAAAAB2Ftb3VudHMAAAAAEAAAAAEAAAAEAAAACgAAAAAAAAAAAAAAAAAAvxgAAAAKAAAAAAAAAAAAAAAAABiuWAAAAAoAAAAAAAAAAAAAAAAAG+8UAAAACgAAAAAAAAAAAAAAAAAAvxgAAAAPAAAABmFzc2V0cwAAAAAAEAAAAAEAAAAMAAAAEgAAAAGwPgtWLZCBl1vshDuSy+xn6Xd2hZYz0nDtJZ7VpetOkwAAABIAAAABHvXvjS+v9myQKh475PC+nz2RxNLwIbon28ulziORTWoAAAASAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABIAAAABd4B7vnYQenf+79HVGkGJydRt2acqUWtPwBwGlyclm4MAAAASAAAAAT/a1Ou0mft6i2wR/KcDK5kBCepAxjOEC+qco9rKtDsvAAAAEgAAAAFuIi3mAl5xcvfAXYXZqz6RkNGtuKPEIC1N1+DKszyWBwAAABIAAAABSM0ICMLZs4XPp064L/XoaAUzbf/HiCr8K084LhSg9ZIAAAASAAAAARVrwGStaF0ANCM2zRvwSZLR5a2t05wbmeQf5XeQnavBAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABIAAAAB9O0Hz7KuOpbsPc8GF10XJ2dKACNB8bSx6bXy9EdPwJcAAAASAAAAAVCQjblpeX30KeFLmwhhkJTn9aHj1m5JpGxYsD8G4/pWAAAADwAAAANvcHMAAAAADQAAADABAAEAAAAAAAcBBQACAAEBAAIDBAMABQQDAQEGAwcDAQgHCQGACgkLBgAKAQMHpTwAAAABAAAAAAAAAAGwPgtWLZCBl1vshDuSy+xn6Xd2hZYz0nDtJZ7VpetOkwAAAAh0cmFuc2ZlcgAAAAMAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAKAAAAAAAAAAAAAAAAABpi+gAAAAAAAAABAAAAAAAAAB8AAAABAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAUlDRQAAAAAALyNnSWbW2znctEwBok1lncPBZuQCamYqP3J17JAJr/0AAAAGAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAEAAAAAEAAAACAAAADwAAAA5Vc2VyUmV3YXJkRGF0YQAAAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAABAAAABgAAAAEKdZzZu6rRGKn43XX9I2sCImVDRtcutjA+zXF8UkMhkwAAABAAAAABAAAAAgAAAA8AAAAOVXNlclJld2FyZERhdGEAAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAEKdZzZu6rRGKn43XX9I2sCImVDRtcutjA+zXF8UkMhkwAAABAAAAABAAAAAgAAAA8AAAAQVXNlclJld2FyZHNTdGF0ZQAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAQAAAAYAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAAQAAAAAQAAAAIAAAAPAAAAEFVzZXJSZXdhcmRzU3RhdGUAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABFWvAZK1oXQA0IzbNG/BJktHlra3TnBuZ5B/ld5Cdq8EAAAAQAAAAAQAAAAIAAAAPAAAAClRpY2tCaXRtYXAAAAAAAAQAAAAUAAAAAQAAAAYAAAABHvXvjS+v9myQKh475PC+nz2RxNLwIbon28ulziORTWoAAAAUAAAAAQAAAAYAAAABIiVn3qcAjXedbLkQF5+FSXNt8YiGDuj8hso4gNJj+BgAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAASIlZ96nAI13nWy5EBefhUlzbfGIhg7o/IbKOIDSY/gYAAAAFAAAAAEAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAFAAAAAEAAAAGAAAAAT/a1Ou0mft6i2wR/KcDK5kBCepAxjOEC+qco9rKtDsvAAAAEAAAAAEAAAACAAAADwAAAApUaWNrQml0bWFwAAAAAAAEAAAAAAAAAAEAAAAGAAAAAUjNCAjC2bOFz6dOuC/16GgFM23/x4gq/CtPOC4UoPWSAAAAFAAAAAEAAAAGAAAAAVCQjblpeX30KeFLmwhhkJTn9aHj1m5JpGxYsD8G4/pWAAAAFAAAAAEAAAAGAAAAAVQouJ306aLOexdFVvv+fiq5uhSAznP35l2HjtXKkLLzAAAAFAAAAAEAAAAGAAAAAXeAe752EHp3/u/R1RpBicnUbdmnKlFrT8AcBpcnJZuDAAAAFAAAAAEAAAAGAAAAAYAXaRDA7RMaHB4h/Yq7yUYY5mSDRjSws/py7vBLlyOEAAAAFAAAAAEAAAAGAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAFAAAAAEAAAAGAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAFAAAAAEAAAAGAAAAAbA+C1YtkIGXW+yEO5LL7Gfpd3aFljPScO0lntWl606TAAAAFAAAAAEAAAAGAAAAAfTtB8+yrjqW7D3PBhddFydnSgAjQfG0sem18vRHT8CXAAAAEAAAAAEAAAACAAAADwAAABBVc2VyUmV3YXJkc1N0YXRlAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAABAAAABgAAAAH07QfPsq46luw9zwYXXRcnZ0oAI0HxtLHptfL0R0/AlwAAABAAAAABAAAAAgAAAA8AAAAQVXNlclJld2FyZHNTdGF0ZQAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAH2qKjDjWz71Dut10ZBTL+vn0NH3viK5Hy92gYqUawX0wAAABQAAAABAAAABwA3ELOD+dp9ZQp/cZp75HkRAmZCeBfrvtYdkkUF/NfHAAAABwe6sw65P50ZSweaPwK6hoIa6CudR3CjjGt7hSTfnihPAAAAB1flEJlJTIyHMT3bhto0yFXWQjE4d89CIkFef3hEchh4AAAAB4Jfx9e7rnJgcACngSZGTIF8R/+az0Pn1vqpYzTvvG5NAAAAB41Yu8WJc5iIphqAQJAhXsOH5kKjZ9wBs018nRP+NBYEAAAAB5+UxXfqJML3HLsMlkycnTIeAkSNH+lGAgr7GJdLHCYCAAAAB64NpahLFYBcXHkxrFZ6jRs0vj8mtIOZPZ/4DLLD3phSAAAAB/EQeDlP0Gs5krQnRhGnxHgJcHvc5hJUz/pt1A/KrTZPAAAAB/eTf46MBtjP0jgzqmEu0HRatu5q32atO/e7r1n9Ya4ZAAAALAAAAAYAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAAQAAAAAQAAAAIAAAAPAAAADldvcmtpbmdCYWxhbmNlAAAAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAEAAAAGAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAEAAAAAEAAAACAAAADwAAAA5Xb3JraW5nQmFsYW5jZQAAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAFAAAAAEAAAAGAAAAARVrwGStaF0ANCM2zRvwSZLR5a2t05wbmeQf5XeQnavBAAAAEAAAAAEAAAACAAAADwAAABRIaXN0b3JpY2FsQ2hlY2twb2ludAAAAAMAAADPAAAAAQAAAAYAAAABFWvAZK1oXQA0IzbNG/BJktHlra3TnBuZ5B/ld5Cdq8EAAAAQAAAAAQAAAAIAAAAPAAAAElJlY2VudE9yYWNsZUJ1Y2tldAAAAAAACQAAAAAAAAAAAAAAAAHHHfAAAAAAAAAABgAAAAEVa8BkrWhdADQjNs0b8EmS0eWtrdOcG5nkH+V3kJ2rwQAAABAAAAABAAAAAgAAAA8AAAASUmVjZW50T3JhY2xlQnVja2V0AAAAAAAJAAAAAAAAAAAAAAAAAccd8QAAAAAAAAAGAAAAARVrwGStaF0ANCM2zRvwSZLR5a2t05wbmeQf5XeQnavBAAAAEAAAAAEAAAACAAAADwAAABJSZWNlbnRPcmFjbGVCdWNrZXQAAAAAAAkAAAAAAAAAAAAAAAABxx3yAAAAAAAAAAYAAAABFWvAZK1oXQA0IzbNG/BJktHlra3TnBuZ5B/ld5Cdq8EAAAAQAAAAAQAAAAIAAAAPAAAAElJlY2VudE9yYWNsZUJ1Y2tldAAAAAAACQAAAAAAAAAAAAAAAAHHHfMAAAAAAAAABgAAAAEVa8BkrWhdADQjNs0b8EmS0eWtrdOcG5nkH+V3kJ2rwQAAABQAAAABAAAABgAAAAEe9e+NL6/2bJAqHjvk8L6fPZHE0vAhuifby6XOI5FNagAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAEAAAAGAAAAAR71740vr/ZskCoeO+Twvp89kcTS8CG6J9vLpc4jkU1qAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAARVrwGStaF0ANCM2zRvwSZLR5a2t05wbmeQf5XeQnavBAAAAAQAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAAB9O0Hz7KuOpbsPc8GF10XJ2dKACNB8bSx6bXy9EdPwJcAAAABAAAABgAAAAE/2tTrtJn7eotsEfynAyuZAQnqQMYzhAvqnKPayrQ7LwAAABQAAAABAAAABgAAAAFIzQgIwtmzhc+nTrgv9ehoBTNt/8eIKvwrTzguFKD1kgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAARVrwGStaF0ANCM2zRvwSZLR5a2t05wbmeQf5XeQnavBAAAAAQAAAAYAAAABSM0ICMLZs4XPp064L/XoaAUzbf/HiCr8K084LhSg9ZIAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAFuIi3mAl5xcvfAXYXZqz6RkNGtuKPEIC1N1+DKszyWBwAAAAEAAAAGAAAAAUjNCAjC2bOFz6dOuC/16GgFM23/x4gq/CtPOC4UoPWSAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAFQkI25aXl99CnhS5sIYZCU5/Wh49ZuSaRsWLA/BuP6VgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABUJCNuWl5ffQp4UubCGGQlOf1oePWbkmkbFiwPwbj+lYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAH07QfPsq46luw9zwYXXRcnZ0oAI0HxtLHptfL0R0/AlwAAAAEAAAAGAAAAAW4iLeYCXnFy98BdhdmrPpGQ0a24o8QgLU3X4MqzPJYHAAAAFAAAAAEAAAAGAAAAAXeAe752EHp3/u/R1RpBicnUbdmnKlFrT8AcBpcnJZuDAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAABAAAABgAAAAF3gHu+dhB6d/7v0dUaQYnJ1G3ZpypRa0/AHAaXJyWbgwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAT/a1Ou0mft6i2wR/KcDK5kBCepAxjOEC+qco9rKtDsvAAAAAQAAAAYAAAABd4B7vnYQenf+79HVGkGJydRt2acqUWtPwBwGlyclm4MAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAYAXaRDA7RMaHB4h/Yq7yUYY5mSDRjSws/py7vBLlyOEAAAAEAAAAAEAAAACAAAADwAAAAhQb29sRGF0YQAAABIAAAABCnWc2buq0Rip+N11/SNrAiJlQ0bXLrYwPs1xfFJDIZMAAAABAAAABgAAAAGAF2kQwO0TGhweIf2Ku8lGGOZkg0Y0sLP6cu7wS5cjhAAAABAAAAABAAAAAgAAAA8AAAAIUG9vbERhdGEAAAASAAAAAW4iLeYCXnFy98BdhdmrPpGQ0a24o8QgLU3X4MqzPJYHAAAAAQAAAAYAAAABgBdpEMDtExocHiH9irvJRhjmZINGNLCz+nLu8EuXI4QAAAAQAAAAAQAAAAIAAAAPAAAACFBvb2xEYXRhAAAAEgAAAAH07QfPsq46luw9zwYXXRcnZ0oAI0HxtLHptfL0R0/AlwAAAAEAAAAGAAAAAYLjuYZsdFQzmgMOhqzc8wVHYGCJu8pGbvMxyKUEVD8iAAAAEAAAAAEAAAACAAAADwAAAA5Vc2VyUmV3YXJkRGF0YQAAAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAABAAAABgAAAAGC47mGbHRUM5oDDoas3PMFR2BgibvKRm7zMcilBFQ/IgAAABAAAAABAAAAAgAAAA8AAAAOVXNlclJld2FyZERhdGEAAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAGC47mGbHRUM5oDDoas3PMFR2BgibvKRm7zMcilBFQ/IgAAABQAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAQp1nNm7qtEYqfjddf0jawIiZUNG1y62MD7NcXxSQyGTAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAE/2tTrtJn7eotsEfynAyuZAQnqQMYzhAvqnKPayrQ7LwAAAAEAAAAGAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABbiIt5gJecXL3wF2F2as+kZDRrbijxCAtTdfgyrM8lgcAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAABsD4LVi2QgZdb7IQ7ksvsZ+l3doWWM9Jw7SWe1aXrTpMAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAABAAAABgAAAAGwPgtWLZCBl1vshDuSy+xn6Xd2hZYz0nDtJZ7VpetOkwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAAQAAAAYAAAAB9O0Hz7KuOpbsPc8GF10XJ2dKACNB8bSx6bXy9EdPwJcAAAAQAAAAAQAAAAMAAAAPAAAAD1Jld2FyZEludkRhdGFWMgAAAAADAAAAAAAAAAUAAAAAAAAAAgAAAAEAAAAGAAAAAfTtB8+yrjqW7D3PBhddFydnSgAjQfG0sem18vRHT8CXAAAAEAAAAAEAAAADAAAADwAAAA9SZXdhcmRJbnZEYXRhVjIAAAAAAwAAAAEAAAAFAAAAAAAAAAAAAAABAAAABgAAAAH07QfPsq46luw9zwYXXRcnZ0oAI0HxtLHptfL0R0/AlwAAABAAAAABAAAAAwAAAA8AAAAPUmV3YXJkSW52RGF0YVYyAAAAAAMAAAACAAAABQAAAAAAAAAAAAAAAQAAAAYAAAAB9O0Hz7KuOpbsPc8GF10XJ2dKACNB8bSx6bXy9EdPwJcAAAAQAAAAAQAAAAIAAAAPAAAADlVzZXJSZXdhcmREYXRhAAAAAAASAAAAAAAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QAAAAEAAAAGAAAAAfTtB8+yrjqW7D3PBhddFydnSgAjQfG0sem18vRHT8CXAAAAEAAAAAEAAAACAAAADwAAAA5Vc2VyUmV3YXJkRGF0YQAAAAAAEgAAAAGqRpZVEHAz1cARc3Y1uKuztarvzinV0Rxv1Tu5Ua4H8gAAAAEAAAAGAAAAAfTtB8+yrjqW7D3PBhddFydnSgAjQfG0sem18vRHT8CXAAAAEAAAAAEAAAACAAAADwAAAA5Xb3JraW5nQmFsYW5jZQAAAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAABAAAABgAAAAH07QfPsq46luw9zwYXXRcnZ0oAI0HxtLHptfL0R0/AlwAAABAAAAABAAAAAgAAAA8AAAAOV29ya2luZ0JhbGFuY2UAAAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAABAAAABgAAAAH07QfPsq46luw9zwYXXRcnZ0oAI0HxtLHptfL0R0/AlwAAABQAAAABBsvDYQAAAAAAAE/gAAAAAABZsLcAAAAB89Gs1QAAAEAE+ydG2/r0v10RbYGuJDd1RZIy5cwkroL3dz81hCnNzHr88sUnRTXhvco7+N06hBbIBRBk9ims4yJarc7orckC",
  },
} as unknown as Horizon.ServerApi.OperationRecord;

/** tx 709f1834: a call to the XOXNO lending controller, not to the router. */
export const lendingRepay = {
  id: "276860755906396161",
  transaction_successful: true,
  source_account: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
  type: "invoke_host_function",
  type_i: 24,
  created_at: "2026-09-16T21:28:36Z",
  transaction_hash:
    "709f18349bf153626d047c27752a48debe77aa485a2ee5dfec3ee52d3b2ed1ec",
  asset_balance_changes: [
    {
      asset_type: "credit_alphanum12",
      asset_code: "USDT0",
      asset_issuer: "GATISXX6BZ6NC7IKQBY37CJD4SOZL3CYZJWXEDG6JVIY4WBS6KXJHN6Q",
      type: "transfer",
      from: "GB6UDJGEBWFPN3OSL5SVXNKP4277ROCGTISGGVL5SORG5ZXT2GWNLIDC",
      to: "CBXRNDQMAJFG4VUKMKFEMFS75UUXE2SPSNV4LEEFCSNBCN66PYRWBKXO",
      amount: "0.0000013",
    },
  ],
  transaction_attr: {
    fee_charged: "35290",
    operation_count: 1,
    envelope_xdr:
      "AAAAAgAAAAB9QaTEDYr27dJfZVu1T+a/+LhGmiRjVX2Tom7m89Gs1QACOCcDsoV+AAAAcQAAAAEAAAAAAAAAAAAAAABqqwsiAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABKCYhvVSuSuftZeO15BMw+kKglEdvaZV4i7UeundGtWIAAAAFcmVwYXkAAAAAAAADAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAAFAAAAAAAAABYAAAAQAAAAAQAAAAEAAAAQAAAAAQAAAAIAAAARAAAAAQAAAAIAAAAPAAAABWFzc2V0AAAAAAAAEgAAAAFknJEO6L6hakXbFSbe6ZW6bdZtDfgJsVRGw6ZHiVM5HQAAAA8AAAAGaHViX2lkAAAAAAADAAAAAQAAAAoAAAAAAAAAAAAAAAAAAAANAAAAAQAAAAAAAAAAAAAAASgmIb1Urkrn7WXjteQTMPpCoJRHb2mVeIu1Hrp3RrViAAAABXJlcGF5AAAAAAAAAwAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAABQAAAAAAAAAWAAAAEAAAAAEAAAABAAAAEAAAAAEAAAACAAAAEQAAAAEAAAACAAAADwAAAAVhc3NldAAAAAAAABIAAAABZJyRDui+oWpF2xUm3umVum3WbQ34CbFURsOmR4lTOR0AAAAPAAAABmh1Yl9pZAAAAAAAAwAAAAEAAAAKAAAAAAAAAAAAAAAAAAAADQAAAAEAAAAAAAAAAWSckQ7ovqFqRdsVJt7plbpt1m0N+AmxVEbDpkeJUzkdAAAACHRyYW5zZmVyAAAAAwAAABIAAAAAAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAEgAAAAFvFo4MAkpuVopiikYWX+0pcmpPk2vFkIUUmhE33n4jYAAAAAoAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAEAAAAAAAAADgAAAAYAAAABKCYhvVSuSuftZeO15BMw+kKglEdvaZV4i7UeundGtWIAAAAQAAAAAQAAAAIAAAAPAAAAC0FjY291bnRNZXRhAAAAAAUAAAAAAAAAFgAAAAEAAAAGAAAAASgmIb1Urkrn7WXjteQTMPpCoJRHb2mVeIu1Hrp3RrViAAAAEAAAAAEAAAACAAAADwAAAAlEZWxlZ2F0ZXMAAAAAAAAFAAAAAAAAABYAAAABAAAABgAAAAEoJiG9VK5K5+1l47XkEzD6QqCUR29plXiLtR66d0a1YgAAABAAAAABAAAAAQAAAA8AAAAQRmxhc2hMb2FuT25nb2luZwAAAAAAAAAGAAAAASgmIb1Urkrn7WXjteQTMPpCoJRHb2mVeIu1Hrp3RrViAAAAEAAAAAEAAAADAAAADwAAAApTcG9rZUFzc2V0AAAAAAADAAAAAQAAABEAAAABAAAAAgAAAA8AAAAFYXNzZXQAAAAAAAASAAAAAWSckQ7ovqFqRdsVJt7plbpt1m0N+AmxVEbDpkeJUzkdAAAADwAAAAZodWJfaWQAAAAAAAMAAAABAAAAAQAAAAYAAAABKCYhvVSuSuftZeO15BMw+kKglEdvaZV4i7UeundGtWIAAAAQAAAAAQAAAAIAAAAPAAAAD1N1cHBseVBvc2l0aW9ucwAAAAAFAAAAAAAAABYAAAABAAAABgAAAAEoJiG9VK5K5+1l47XkEzD6QqCUR29plXiLtR66d0a1YgAAABQAAAABAAAABgAAAAEsKRv/BjVtchn2brPmnKXIU+Qs8RHAcQX6Q9FPHLtHuQAAABAAAAABAAAAAgAAAA8AAAAFT3duZXIAAAAAAAADAAAAFgAAAAEAAAAGAAAAASwpG/8GNW1yGfZus+acpchT5CzxEcBxBfpD0U8cu0e5AAAAFAAAAAEAAAAGAAAAAWSckQ7ovqFqRdsVJt7plbpt1m0N+AmxVEbDpkeJUzkdAAAAFAAAAAEAAAAGAAAAAW8WjgwCSm5WimKKRhZf7Slyak+Ta8WQhRSaETfefiNgAAAAEAAAAAEAAAACAAAADwAAAAZQYXJhbXMAAAAAABEAAAABAAAAAgAAAA8AAAAFYXNzZXQAAAAAAAASAAAAAWSckQ7ovqFqRdsVJt7plbpt1m0N+AmxVEbDpkeJUzkdAAAADwAAAAZodWJfaWQAAAAAAAMAAAABAAAAAQAAAAYAAAABbxaODAJKblaKYopGFl/tKXJqT5NrxZCFFJoRN95+I2AAAAAUAAAAAQAAAAcDqGMP9CQ5t0hNfPSXHjMRUEp5qY25uIyBqw7+dI+P4wAAAAe5Om5s+JvqR5+H+8B4HTBYJX4AGi/gQbWx7gDkuRkkPAAAAAfChXdAcXqHtYwgsR5o26zU9KstoaHN4D8LwXmoqfESKAAAAAUAAAABAAAAAH1BpMQNivbt0l9lW7VP5r/4uEaaJGNVfZOibubz0azVAAAAAlVTRFQwAAAAAAAAAAAAAAAmiV7+DnzRfQqAcb+JI+SdlexYym1yDN5NUY5YMvKukwAAAAYAAAABKCYhvVSuSuftZeO15BMw+kKglEdvaZV4i7UeundGtWIAAAAQAAAAAQAAAAIAAAAPAAAAD0JvcnJvd1Bvc2l0aW9ucwAAAAAFAAAAAAAAABYAAAABAAAABgAAAAEoJiG9VK5K5+1l47XkEzD6QqCUR29plXiLtR66d0a1YgAAABAAAAABAAAAAwAAAA8AAAAKU3Bva2VVc2FnZQAAAAAAAwAAAAEAAAARAAAAAQAAAAIAAAAPAAAABWFzc2V0AAAAAAAAEgAAAAFknJEO6L6hakXbFSbe6ZW6bdZtDfgJsVRGw6ZHiVM5HQAAAA8AAAAGaHViX2lkAAAAAAADAAAAAQAAAAEAAAAGAAAAAWSckQ7ovqFqRdsVJt7plbpt1m0N+AmxVEbDpkeJUzkdAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABbxaODAJKblaKYopGFl/tKXJqT5NrxZCFFJoRN95+I2AAAAABAAAABgAAAAFvFo4MAkpuVopiikYWX+0pcmpPk2vFkIUUmhE33n4jYAAAABAAAAABAAAAAgAAAA8AAAAFU3RhdGUAAAAAAAARAAAAAQAAAAIAAAAPAAAABWFzc2V0AAAAAAAAEgAAAAFknJEO6L6hakXbFSbe6ZW6bdZtDfgJsVRGw6ZHiVM5HQAAAA8AAAAGaHViX2lkAAAAAAADAAAAAQAAAAEASiQ9AAAAfAAABEAAAAAAAACxhwAAAAHz0azVAAAAQByyD9sKMkzaQhonYkRoKYBNv9f+81g/+jtpOF1u2galiK0FFr9Kl/wz22vKpaKcnywSaIZ4/BIn1Be2UJui/wo=",
  },
} as unknown as Horizon.ServerApi.OperationRecord;

/**
 * The transaction meta of tx efb32c1f as Stellar Expert serves it
 * (`/explorer/public/tx/<hash>`, field `meta`): a v4 TransactionMeta, trimmed to
 * its operation's token `transfer` events (11 of the 27 events; ledger changes,
 * pool trade events and diagnostics dropped). The last event pays 1608622 XAUM
 * base units (0.001608622) from the router to the swapper.
 */
export const usdcToXaumMeta =
  "AAAABAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAACwAAAAAAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAABAAAAAAAAAAQAAAAPAAAACHRyYW5zZmVyAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAADgAAAD1VU0RDOkdBNVpTRUpZQjM3SlJDNUFWQ0lBNU1PUDRSSFRNMzM1WDJLR1gzSUhPSkFQUDVSRTM0SzRLWlZOAAAAAAAACgAAAAAAAAAAAAAAAAQGq8UAAAAAAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAAQAAAAAAAAAEAAAADwAAAAh0cmFuc2ZlcgAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAASAAAAATz6JWHCsqoRS8pYoOVkU/TpnA0ZHWkUvOFnLC1QehAhAAAADgAAAD1VU0RDOkdBNVpTRUpZQjM3SlJDNUFWQ0lBNU1PUDRSSFRNMzM1WDJLR1gzSUhPSkFQUDVSRTM0SzRLWlZOAAAAAAAACgAAAAAAAAAAAAAAAAQGq8UAAAAAAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAAAQAAAAAAAAAEAAAADwAAAAh0cmFuc2ZlcgAAABIAAAABPPolYcKyqhFLylig5WRT9OmcDRkdaRS84WcsLVB6ECEAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAADgAAAAZuYXRpdmUAAAAAAAoAAAAAAAAAAAAAAAARcv2TAAAAAAAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAAAEAAAAAAAAABAAAAA8AAAAIdHJhbnNmZXIAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAEgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAAA4AAAAGbmF0aXZlAAAAAAAKAAAAAAAAAAAAAAAAEXL9kwAAAAAAAAAB5qfZ63UjAGpGmqdIOtEQckdEPA2C5idj3mcISMTpfJAAAAABAAAAAAAAAAQAAAAPAAAACHRyYW5zZmVyAAAAEgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAAOAAAAPUVVUkM6R0RIVTZXUkc0SUVRWE01Tlo0Qk1QS09YSFc3Nk1aTTRZMklFTUZEVlhCU0RQNlNKWTRJVE5QUDIAAAAAAAAKAAAAAAAAAAAAAAAAA5A7SwAAAAAAAAAB5qfZ63UjAGpGmqdIOtEQckdEPA2C5idj3mcISMTpfJAAAAABAAAAAAAAAAQAAAAPAAAACHRyYW5zZmVyAAAAEgAAAAFRKi8O7k0t6tNogsIUTVNkstxQ5ndz1G/l+FW+RALNLAAAABIAAAAAAAAAADTetyvSDVP8tjBO7LbxyvVynXhBbi7c1NCdRkBK+wCaAAAADgAAAD1FVVJDOkdESFU2V1JHNElFUVhNNU5aNEJNUEtPWEhXNzZNWk00WTJJRU1GRFZYQlNEUDZTSlk0SVROUFAyAAAAAAAACgAAAAAAAAAAAAAAAAAElYYAAAAAAAAAAean2et1IwBqRpqnSDrREHJHRDwNguYnY95nCEjE6XyQAAAAAQAAAAAAAAAEAAAADwAAAAh0cmFuc2ZlcgAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAASAAAAAZ7eNbKCl7Wt85PmVWFXjsoV7+CiyefPJ9wHrjHnvATeAAAADgAAAD1FVVJDOkdESFU2V1JHNElFUVhNNU5aNEJNUEtPWEhXNzZNWk00WTJJRU1GRFZYQlNEUDZTSlk0SVROUFAyAAAAAAAACgAAAAAAAAAAAAAAAAOQO0sAAAAAAAAAAcuaVl3DV3p+pGqdQZHHEkyoNrQNh/UxvifzFyn4eVcaAAAAAQAAAAAAAAAEAAAADwAAAAh0cmFuc2ZlcgAAABIAAAABnt41soKXta3zk+ZVYVeOyhXv4KLJ588n3AeuMee8BN4AAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAADgAAAD1zVVNEOkdDSFc3Q1dJN0dNSVlRWUZYTUZKTkpYNTY0NVhHV0lJTklBRVFLM1NBQlFPNkNBWUw1VDdKWUlIAAAAAAAACgAAAAAAAAAAAAAAAAQI3/sAAAAAAAAAAcuaVl3DV3p+pGqdQZHHEkyoNrQNh/UxvifzFyn4eVcaAAAAAQAAAAAAAAAEAAAADwAAAAh0cmFuc2ZlcgAAABIAAAABqkaWVRBwM9XAEXN2Nbirs7Wq784p1dEcb9U7uVGuB/IAAAASAAAAATh6wnU8LDRmUIQDfBxA4Lo/V1k0TpghR6jYElxMKfjcAAAADgAAAD1zVVNEOkdDSFc3Q1dJN0dNSVlRWUZYTUZKTkpYNTY0NVhHV0lJTklBRVFLM1NBQlFPNkNBWUw1VDdKWUlIAAAAAAAACgAAAAAAAAAAAAAAAAQI3/sAAAAAAAAAAbUQmw0RQiqRqBr6EobPPx1Ms1QG3D0rTe8MtlhC4qz6AAAAAQAAAAAAAAADAAAADwAAAAh0cmFuc2ZlcgAAABIAAAABOHrCdTwsNGZQhAN8HEDguj9XWTROmCFHqNgSXEwp+NwAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAEQAAAAEAAAACAAAADwAAAAZhbW91bnQAAAAAAAoAAAAAAAAAAAAAAAAAGIuuAAAADwAAAAt0b19tdXhlZF9pZAAAAAABAAAAAAAAAAG1EJsNEUIqkaga+hKGzz8dTLNUBtw9K03vDLZYQuKs+gAAAAEAAAAAAAAAAwAAAA8AAAAIdHJhbnNmZXIAAAASAAAAAapGllUQcDPVwBFzdjW4q7O1qu/OKdXRHG/VO7lRrgfyAAAAEgAAAAAAAAAAfUGkxA2K9u3SX2VbtU/mv/i4RpokY1V9k6Ju5vPRrNUAAAARAAAAAQAAAAIAAAAPAAAABmFtb3VudAAAAAAACgAAAAAAAAAAAAAAAAAYi64AAAAPAAAAC3RvX211eGVkX2lkAAAAAAEAAAAAAAAAAQAAAAEAAAAAAAAAAAABvCMAAAAAAAQq3AAAAAAAA815AAAAAQAAAAoAAAAAAAAAAAAAAAAAGIuuAAAAAAAAAAA=";

type MetaWire = ReturnType<xdr.TransactionMeta["toXdrObject"]>;
type V4Wire = Extract<MetaWire, { v: 4 }>["v4"];
type EventWire = V4Wire["operations"][number]["events"][number];

/** An account other than the swapper, for a transfer that is not the viewer's. */
export const OTHER_ACCOUNT =
  "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H";

/** The decoded v4 meta of `usdcToXaumMeta`. */
export const realV4 = (): V4Wire => {
  const wire = xdr.TransactionMeta.fromXDR(
    usdcToXaumMeta,
    "base64",
  ).toXdrObject();
  if (wire.v !== 4) throw new Error("the fixture is a v4 meta");

  return wire.v4;
};

/** `usdcToXaumMeta` with its last event (the XAUM transfer from the router to the swapper) edited. */
export const withLastEvent = (
  edit: (event: EventWire) => EventWire,
): string => {
  const v4 = realV4();
  const [{ events }] = v4.operations;
  events[events.length - 1] = edit(events[events.length - 1]);

  return xdr.TransactionMeta.fromXdrObject({ v: 4, v4 }).toXDR("base64");
};

/** `usdcToXaumMeta` rewritten as a v3 meta, whose events sit on its Soroban meta. */
export const asV3 = (): string => {
  const v4 = realV4();

  return xdr.TransactionMeta.fromXdrObject({
    v: 3,
    v3: {
      ext: v4.ext,
      txChangesBefore: [],
      operations: [{ changes: [] }],
      txChangesAfter: [],
      sorobanMeta: {
        ext: { v: 0 },
        events: v4.operations[0].events,
        returnValue: nativeToScVal(null).toXdrObject(),
        diagnosticEvents: [],
      },
    },
  }).toXDR("base64");
};
